### ISSUE TITLE
Include not as a plugin

### ISSUE THREAD

**Issue by K15Lmk98** [serkanalgur/cmb2-field-faiconselect#1]
This is an automatic translation.

Excellent work Serkanalgur, thank you.

Is it possible to include it directly - not as a plugin -?

I tried this code in my Child Theme Genesis, but it does not load it:

require_once("vendor/cmb2/cmb2-field-type-font-awesome/iconselect.php");

Claudio_

**Comment by serkanalgur** [comment]
It'is possible actually,

you need yo change `$asset_path` definition in `Sesetup_my_cssjs()` function in `iconselect.php`.

from
```php
$asset_path = apply_filters( 'sa_cmb2_field_faiconselect_asset_path', plugins_url( '', __FILE__  ) );
 ```
to 

```php
$file = __DIR__; 
$asset_path = str_replace( WP_CONTENT_DIR, WP_CONTENT_URL, $file );
```

**Comment by K15Lmk98** [comment]
Thank you.
Claudio_
