### ISSUE TITLE
Don't work with groups

### ISSUE THREAD

**Issue by gurkankara** [serkanalgur/cmb2-field-faiconselect#2]
Hi, i use the iconselect in group field type. Bu when i add new group entry, just first iconselect is clickable. Others are not. Therefore i can't select icon until i saved the options.

-----------
Merhaba Serkan, group alanı içinde kullandığımda font seçemiyorum. Ayarları kaydettiğimde ise kaydedilen ayarlar için ikon seçebiliyorum. Nasıl düzeltebiliriz?

**Comment by serkanalgur** [comment]
Thanks for your feedback. Give me some time to fix this bug. I will inform you.
___
Selam, selectlerin eklenme şeklini değiştirebilirim. Gün içinde halletmiş olurum.

**Comment by serkanalgur** [comment]
Please try this new version of plugin. I think the problem solved. I'am closing this issue.
___
Yeni versiyonu denersen memnun olurum. Kodu düzelttim. açılmış olan bu konuyu kapatıyorum.
