### ISSUE TITLE
Font Awesome 5.x

### ISSUE THREAD

**Issue by cocodedesigns** [serkanalgur/cmb2-field-faiconselect#4]
Hi,

I am looking at integrating this plugin into my theme, but I am having a few problems. I noticed another issue where you explain how to integrate it without using the plugin (which helps me no end, thank you).  But I am trying to use my own download of Font Awesome 5 (v5.7.2).  Just to check, you have a predefined array of icons.  Would I need to go through and write my own array should I wish to use the field, or would the field automatically pick up on each of the icons listed in the CSS file?  If it is the former, that's fine (even if it will be a pain in the derriere to define each of the new icons manually), but I would hope the latter is possible.

As a related aside, since this plugin is currently using 4.7.x version of Font Awesome, is there a possibility of moving to the 5.x versions in the future?

**Comment by serkanalgur** [comment]
Hello there,

I looked at my instructions and code, yes you are right about missing instructions. I have a filter about asset paths, but I did not write anything about it 🙁.  Thank you for your issue.

I can extend this plugin for using Font Awesome 5. Also, I can prepare a predefined class list for Font Awesome 5. Give me some time, please 😇.

**Comment by serkanalgur** [comment]
Check the new version of the plugin. Please inform me about your thoughts. I'm closing this issue.
