### ISSUE TITLE
Registrer on composer

### ISSUE THREAD

**Issue by cehojac** [serkanalgur/cmb2-field-faiconselect#5]
Please registrer your cmb2-field-faiconselect in composer. i make plugins whit composer and CMB2 . Thank You

**Comment by serkanalgur** [comment]
Hello @cehojac 	This plugin is available on wppackagist. 

https://wpackagist.org/search?q=cmb2-field-type-font-awesome

Please read documentation on https://wpackagist.org/

**Comment by cehojac** [comment]
@serkanalgur please registrer it on https://packagist.org/ Thanks.

**Comment by serkanalgur** [comment]
Plugin registered on [Packagist](https://packagist.org/packages/serkanalgur/cmb2-field-faiconselect) I will add instructions to README. Closing this issue. Thanks

**Comment by cehojac** [comment]
Thank you!
